Updated event.py to handle app_terminated_event.
As of now, when the event stream gets a  app_terminated_event, it raises an exeption : 
MarathonError: Unknown event_type: app_terminated_event, data: {u'eventType': u'app_terminated_event', u'timestamp': u'2017-02-23T08:54:44.470Z', u'appId': u'/longtest/ms/beds-node'}
This fixs it.